# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17da8e02287355699d2bf4582c9ce982a3163a1615e20db01bd44240ba43a7e4a3c2a776a1874cad623ab3b422e42d035ce26e4851695ef41a53773d40a71770

test:
  secret_key_base: 7e0bce6c44ccba5a8ea22c4e043d650837fe845d4617c9d52eda76fe15494f8ed0e0dd14c02979d9ee0e6fa3c2d83d108a50b97719baf36886e8e613e19b8b0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
